### ISSUE TITLE
Use "white-space: pre" css style on result tables

### ISSUE THREAD

**Issue by tonylampada** [epantry/django-sql-explorer#144]
Sometimes cells in the resultset have whitespace characters that are meaningful. This is particcularly true for `explain` queries
I'm using css-stylebot with the following rule:

```css
.floatThead-container, .floatThead-wrapper {
    white-space: pre;
}
```

It would be nice to have that behaviour by default.

With the css "hack":
![pretty](http://i.imgur.com/layEeni.png)

Without it
![not so pretty](http://i.imgur.com/CxZZSIo.png)
